# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import typing

class PySurrealFs:
    @classmethod
    def connect_ws(cls, url:str, namespace:typing.Optional[str] = ..., database:typing.Optional[str] = ...) -> PySurrealFs:
        ...

    @classmethod
    def mem(cls, namespace:typing.Optional[str] = ..., database:typing.Optional[str] = ...) -> PySurrealFs:
        ...

    def ls(self, path:typing.Optional[str], all:typing.Optional[bool], long:typing.Optional[bool], recursive:typing.Optional[bool], dir_only:typing.Optional[bool], human:typing.Optional[bool]) -> str:
        ...

    def cat(self, path:str) -> str:
        ...

    def cat_bytes(self, path:str) -> bytes:
        ...

    def tail(self, path:str, n:typing.Optional[int]) -> str:
        ...

    def read(self, path:str, offset:int, limit:int) -> str:
        ...

    def nl(self, path:str, start:typing.Optional[int]) -> str:
        ...

    def grep(self, pattern:str, path:str, recursive:typing.Optional[bool]) -> str:
        ...

    def touch(self, path:str) -> str:
        ...

    def write_file(self, path:str, content:str) -> str:
        ...

    def write_bytes(self, path:str, data:bytes) -> str:
        ...

    def edit(self, path:str, old:str, new:str, replace_all:typing.Optional[bool]) -> str:
        ...

    def mkdir(self, path:str, parents:bool) -> str:
        ...

    def cp(self, src:str, dest:str) -> str:
        ...

    def cd(self, target:str) -> str:
        ...

    def pwd(self) -> str:
        ...

    def glob(self, pattern:str) -> str:
        ...

    def curl(self, url:str, follow:typing.Optional[bool], headers:typing.Optional[typing.Sequence[tuple[str, str]]], data:typing.Optional[str], method:typing.Optional[str], out:typing.Optional[str], auto_name:typing.Optional[bool]) -> str:
        ...


